import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="origin-trial" content="YOUR_ORIGIN_TRIAL_TOKEN_HERE" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-full overflow-hidden`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
